### ISSUE TITLE
Website Is Down

### ISSUE THREAD

**Issue by 3h6-1** [ipatch/theairportwiki#2]
It used to work, but now, whenever I go to theairportwiki.com, this is what it says:

### Hello, theairportwiki.com !
mediawiki site is no more, most if not all content that was there is [here](https://github.com/ipatch/theairportwiki)

**Comment by ipatch** [comment]
yeah i took down the mediawiki site a while back, as it is something i do not want to maintain anymore.  pretty much all content that was on that site is contained here within this repo.

Is there something specific you are looking for?

**Comment by 3h6-1** [comment]
No not really. I wasn't sure if it was intended so I just wanted to let you know.
